title: Manejo de los principales problemas de salud en el Fenómeno El Niño en la población asegurada
description: Módulo de autoaprendizaje sobre las principales enfermedades ligadas al Fenómeno El Niño
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
